### ISSUE TITLE
ok, can you tell me what will be the next steps?

### ISSUE THREAD

**Issue by atherdon** [guruduttperi/Meal_Planning_UX_Build_2#1]

**Comment by guruduttperi** [comment]
For this, the next step would be for developers to build this system. If you want me to work on some more design stuff, I can. I am making the mobile version of this design - which is to be developed using React Native.

**Comment by atherdon** [comment]
ok, post here when you'll finish some drafts related to mobile part. But i plan to create mobile app by using some UI kits, because it'll save your time and time of our devs, because they'll be able to use code, that was created before...
Btw, check this: https://angel.co/projects/764907-meal-planning-app-ui?src=startup_profile

**Comment by guruduttperi** [comment]
Hi,

Thank you for posting the design! I've made some progress with the mobile design. You can look at it here: 
https://github.com/guruduttperi/Meal_Planning_UX_Mobile/
Here is an online/HTML working prototype: https://guruduttperi.github.io/Meal_Planning_UX_Mobile
Here are individual files, hosted on Invision: https://invis.io/JVLI1UC6CNA

Hope you like it!
